#$ -N SkeptikNDc                    # declares job name                
#$ -pe mpich 16                     # requests 16 cores
#$ -V                               # imports all environment variables
#$ -M skeptik-dev@googlegroups.com  # email address to be notified
#$ -m beas                          # notifies of job's beginning, end, abortion and rescheduling
#$ -l h_rt=00:02:00                 # runs job for a maximum time of hh:mm:ss

java -jar ../../skeptik.jar
